export const provinces = [
  "Buenos Aires",
  "Catamarca",
  "Chaco",
  "Chubut",
  "Ciudad Autónoma de Buenos Aires",
  "Córdoba",
  "Corrientes",
  "Entre Ríos",
  "Formosa",
  "Jujuy",
  "La Pampa",
  "La Rioja",
  "Mendoza",
  "Misiones",
  "Neuquén",
  "Río Negro",
  "Salta",
  "San Juan",
  "San Luis",
  "Santa Cruz",
  "Santa Fe",
  "Santiago del Estero",
  "Tierra del Fuego",
  "Tucumán",
];

const localities: Record<string, string[]> = {
  "Buenos Aires": [
    "25 de Mayo",
    "9 de Julio",
    "Adolfo Alsina",
    "Adolfo Gonzales Chaves",
    "Alberti",
    "Almirante Brown",
    "Avellaneda",
    "Bahía Blanca",
    "Balcarce",
    "Baradero",
    "Barrio Segunda Usina",
    "Benito Juárez",
    "Berazategui",
    "Berisso",
    "Bolívar",
    "Bragado",
    "Brandsen",
    "Campana",
    "Cañuelas",
    "Capitán Sarmiento",
    "Carlos Casares",
    "Carlos Tejedor",
    "Carmen de Areco",
    "Castelli",
    "Chascomús",
    "Chivilcoy",
    "Colón",
    "Coronel Dorrego",
    "Coronel Pringles",
    "Coronel Suárez",
    "Daireaux",
    "Dolores",
    "Ensenada",
    "Escobar",
    "Esteban Echeverría",
    "Exaltación de la Cruz",
    "Florencio Varela",
    "Florentino Ameghino",
    "General Alvarado",
    "General Alvear",
    "General Arenales",
    "General Belgrano",
    "General La Madrid",
    "General Las Heras",
    "General Lavalle",
    "General Paz",
    "General Pinto",
    "General Rodríguez",
    "General San Martín",
    "General Viamonte",
    "General Villegas",
    "Guaminí",
    "Hipólito Yrigoyen",
    "Hurlingham",
    "Ituzaingó",
    "José Clemente Paz",
    "Juárez",
    "La Matanza",
    "La Plata",
    "Lanús",
    "Lobos",
    "Lomas de Zamora",
    "Luján",
    "Magdalena",
    "Maipú",
    "Mar Chiquita",
    "Mar del Plata",
    "Marcos Paz",
    "Mercedes",
    "Merlo",
    "Monte",
    "Monte Hermoso",
    "Moreno",
    "Morón",
    "Navarro",
    "Nueve de Julio",
    "Olavarría",
    "Patagones",
    "Pehuajó",
    "Pellegrini",
    "Pergamino",
    "Pila",
    "Pilar",
    "Pinamar",
    "Presidente Perón",
    "Puán",
    "Quilmes",
    "Ramallo",
    "Rauch",
    "Rivadavia",
    "Rojas",
    "Roque Pérez",
    "Saavedra",
    "Saladillo",
    "Salliqueló",
    "Salto",
    "San Andrés de Giles",
    "San Antonio de Areco",
    "San Cayetano",
    "San Fernando",
    "San Isidro",
    "San Nicolás",
    "San Pedro",
    "San Vicente",
    "Suárez",
    "Tandil",
    "Tapalqué",
    "Tigre",
    "Tordillo",
    "Tornquist",
    "Treinta y Tres",
    "Vicente López",
    "Villa Gesell",
    "Villarino",
    "Zárate",
  ],
  "Catamarca": [
    "Agua de Dinero",
    "Alto de la Jaula",
    "Andalgalá",
    "Antofagasta de la Sierra",
    "Belén",
    "Cafayate",
    "Capayán",
    "Chumbicha",
    "Coronel Díaz",
    "El Bolsón",
    "El Rodeo",
    "Fiambalá",
    "Hualfín",
    "Icaño",
    "Jacinto Arauz",
    "La Carrera",
    "La Ciénaga",
    "La Higuera",
    "La Paz",
    "La Puerta de San José",
    "Las Juntas",
    "Lavalle",
    "Los Altos",
    "Los Varela",
    "Manuel Belgrano",
    "Mutquín",
    "Paclín",
    "Pomán",
    "Puerta de Corral Quemado",
    "Recreo",
    "Río de la Puerta",
    "San Fernando del Valle de Catamarca",
    "San Fernando",
    "San José",
    "San Martín",
    "Saujil",
    "Tapso",
    "Tinogasta",
    "Villa Belgrano",
    "Villa Calchaquí",
    "Villa Dolores",
    "Villa General Belgrano",
    "Villa San Roque",
  ],
  "Chaco": [
    "Avia Terai",
    "Barranqueras",
    "Basail",
    "Campo Largo",
    "Capitán Solari",
    "Charadai",
    "Charata",
    "Chorotis",
    "Ciudad de Güiraldes",
    "Colonel Brandsen",
    "Comandancia Fontana",
    "Corzuela",
    "El Espinillo",
    "El Colorado",
    "El Sauzalito",
    "Fontana",
    "Fuerte Esperanza",
    "Gancedo",
    "General Capdevila",
    "General Güemes",
    "General Isidoro Suárez",
    "General San Martín",
    "Hermoso Campo",
    "Itin",
    "Juan José Castelli",
    "La Clotilde",
    "La Leonesa",
    "La Tigra",
    "La Verde",
    "Lapachito",
    "Las Breñas",
    "Las Garcitas",
    "Las Palmas",
    "Loma Alta",
    "Lomas de Galarza",
    "Los Frentones",
    "Machagai",
    "Makallé",
    "Manuel J. Formosa",
    "Miranda",
    "Misión San Fernando",
    "Monte Quemado",
    "Nueva Pompeya",
    "Paraje El Tigre",
    "Paraje San Martín",
    "Pampa del Indio",
    "Pampa San Martín",
    "Presidencia de la Plaza",
    "Presidencia Roca",
    "Presidencia Roque Sáenz Peña",
    "Puerto Vilelas",
    "Quitilipi",
    "Remorino",
    "Río Bermejito",
    "Río Teuco",
    "Saenz Peña",
    "San Bernardo",
    "San Jorge",
    "San Ramón de la Nueva Orán",
    "Santa Sylvina",
    "Taco Pozo",
    "Tres Isletas",
    "Villa Berthet",
    "Villa Río Bermejito",
  ],
  "Chubut": [
    "Aldea Beleiro",
    "Aldea Escolar",
    "Aldea Emilio",
    "Aldea Lepá",
    "Aldea Valle del Fuego",
    "Armada Argentina",
    "Barrio Crear",
    "Barrio Güemes",
    "Barrio Islas Malvinas",
    "Barrio Laprida",
    "Barrio Mitre",
    "Barrio Saavedra",
    "Buen Pasto",
    "Camarones",
    "Cañadón Grande",
    "Cañadón Lagarto",
    "Cañadón Maitén",
    "Cañadón Pescado",
    "Cañadón Quillén",
    "Capitán alemán",
    "Cholila",
    "Colán Conhué",
    "Colhué Huapi",
    "Comodoro Rivadavia",
    "Corcovado",
    "Cushamen",
    "Diadema Argentina",
    "El Bolsón",
    "El Hoyo",
    "El Maitén",
    "Epuyén",
    "Esperanza",
    "Facundo",
    "Gaimán",
    "Gan Gan",
    "Gobernador Costa",
    "Gobernador Gregores",
    "Gobernador Moyano",
    "Gualjaina",
    "Hoyo de Epuyén",
    "Hoyo de Esquina",
    "Jaramillo",
    "Lago Blanco",
    "Lago Puelo",
    "Lago Rosario",
    "Lago Sarmiento",
    "Laguna Chica",
    "Laguna Palacios",
    "Lanín",
    "Laprida",
    "Las Chapas",
    "Las Plumas",
    "Los Altos",
    "Los Berracos",
    "Los Cipreses",
    "Los Corralitos",
    "Los Tres Picos",
    "Mártires",
    "Malaspina",
    "Marchiquita",
    "Mirador",
    "Paso de Indios",
    "Paso del Sapo",
    "Playa Magagna",
    "Playa Unión",
    "Puerto Madryn",
    "Puerto Py",
    "Puerto Santa Elena",
    "Río Mayo",
    "Río Pico",
    "Rawson",
    "Sarmiento",
    "Sepaucal",
    "Teckel",
    "Telsen",
    "Trelew",
    "Trevelin",
    "Villa Aldea Escolar",
    "Villa El Hoyo",
    "Villa Languinelo",
    "Villa Mañquiza",
    "Villa Paso",
    "Villa Petroquímica",
    "Villa Rivadavia",
    "Villa San Isidro",
    "Villa Sarmiento",
    "Yala",
    "Yubatá",
  ],
  "Ciudad Autónoma de Buenos Aires": [
    "Agronomía",
    "Almagro",
    "Balvanera",
    "Barracas",
    "Belgrano",
    "Boedo",
    "Caballito",
    "Chacarita",
    "Coghlan",
    "Colegiales",
    "Constitución",
    "Flores",
    "Floresta",
    "La Boca",
    "La Paternal",
    "Liniers",
    "Mataderos",
    "Monte Castro",
    "Monserrat",
    "Nueva Pompeya",
    "Núñez",
    "Palermo",
    "Parque Avellaneda",
    "Parque Chacabuco",
    "Parque Chas",
    "Parque Patricios",
    "Puerto Madero",
    "Recoleta",
    "Retiro",
    "Saavedra",
    "San Cristóbal",
    "San Nicolás",
    "San Telmo",
    "Vélez Sársfield",
    "Versalles",
    "Villa Crespo",
    "Villa del Parque",
    "Villa Devoto",
    "Villa General Mitre",
    "Villa Lugano",
    "Villa Luro",
    "Villa Ortúzar",
    "Villa Pueyrredón",
    "Villa Real",
    "Villa Riachuelo",
    "Villa Santa Rita",
    "Villa Soldati",
    "Villa Urquiza",
  ],
  "Córdoba": [
    "Alcira Gigena",
    "Aldea Brasilera",
    "Aldea María Luisa",
    "Aldea Santa María",
    "Alta Gracia",
    "Arias",
    "Arroyito",
    "Balnearia",
    "Bell Ville",
    "Bialet Massé",
    "Bouwer",
    "Brinkmann",
    "Camilo Aldao",
    "Cañada de Gómez",
    "Cañada del Sauce",
    "Capilla del Sauce",
    "Carl Júarez",
    "Carnaza",
    "Carrilobo",
    "Cavanagh",
    "Cerro Colorado",
    "Chaján",
    "Chalacea",
    "Chañarcito",
    "Chucul",
    "Cinco Saltos",
    "Cipolletti",
    "Colonia Almada",
    "Colonia Ana",
    "Colonia Barge",
    "Colonia Caroya",
    "Colonia Italiana",
    "Colonia Tirolesa",
    "Colonia Vignale",
    "Comechingones",
    "Concepción",
    "Conlara",
    "Corral de Bustos",
    "Corralito",
    "Cosquín",
    "Córdoba",
    "Cruz del Eje",
    "Deán Funes",
    "Del Campillo",
    "Despeñaderos",
    "Devoto",
    "Dique Chico",
    "Dumesnil",
    "El Tío",
    "Elena",
    "Embalse",
    "Escuela Argentina King",
    "Esquina",
    "Estación General Paz",
    "Estancia Vieja",
    "Fray Cayetano Scáneri",
    "General Baldissera",
    "General Levalle",
    "General Roca",
    "General Roca (San Javier)",
    "Guatimozín",
    "Hernando",
    "Huanchillas",
    "Huerta Grande",
    "Huinca Renancó",
    "Ifflinger",
    "Iriondo",
    "Isla Verde",
    "James Craik",
    "Jesús María",
    "Jockey Club",
    "Juárez Celman",
    "La Calera",
    "La Carlota",
    "La Granja",
    "La Higuera",
    "La Para",
    "La Paquita",
    "La Puerta",
    "La Tordilla",
    "Laborde",
    "Laboulaye",
    "Laguna Larga",
    "Las Caleras",
    "Las Higueras",
    "Las Mostazas",
    "Las Perdices",
    "Las Varas",
    "Las Varillas",
    "Leones",
    "Los Cocos",
    "Los Cuchilleros",
    "Los Hornillos",
    "Los Hoyos",
    "Los Molinos",
    "Los Quadros",
    "Los Sauces",
    "Lutti",
    "Luque",
    "Malvinas Argentinas",
    "Manchaca",
    "Manfredi",
    "Maquinista Savio",
    "Marcos Juárez",
    "Mendiolaza",
    "Mina Clavero",
    "Miramar",
    "Morrison",
    "Monte Buey",
    "Monte Cristo",
    "Monte de los Gauchos",
    "Montecristo",
    "Morteros",
    "Nono",
    "Obispo Trejo",
    "Olaeta",
    "Oliva",
    "Oncativo",
    "Pampayasta",
    "Panaholma",
    "Pascanas",
    "Pilar",
    "Pilar (Córdoba)",
    "Punta del Agua",
    "Río Cuarto",
    "Río Segundo",
    "Río Tercero",
    "Roma",
    "Rumipal",
    "Sacsardí",
    "Sacanta",
    "San Agustín",
    "San Antonio de Arredondo",
    "San Antonio de Litín",
    "San Basilio",
    "San Carlos Minas",
    "San Clemente",
    "San Esteban",
    "San Francisco",
    "San Francisco del Chañar",
    "San Jerónimo",
    "San Javier",
    "San Joaquín",
    "San José de la Dormida",
    "San José de las Salinas",
    "San Lorenzo",
    "San Marcos Sierras",
    "San Marcos Sud",
    "San Nicolás",
    "San Pedro",
    "San Pedro (Punilla)",
    "San Roque",
    "Santa María de Punilla",
    "Santa Rosa de Calamuchita",
    "Santa Rosa de Río Primero",
    "Santiago del Estero",
    "Sarmiento",
    "Saturnino María Laspiur",
    "Seeber",
    "Sevilla",
    "Saldán",
    "Siqueira",
    "Tancacha",
    "Tartagal",
    "Ticino",
    "Tilín",
    "Toledo",
    "Tosquita",
    "Tres Esquinas",
    "Tránsito",
    "Tuclame",
    "Ucacha",
    "Unquillo",
    "Valle Hermoso",
    "Villa Allende",
    "Villa Atuel",
    "Villa California",
    "Villa Carlos Paz",
    "Villa Candelaria",
    "Villa de Soto",
    "Villa del Totoral",
    "Villa del Rosario",
    "Villa General Belgrano",
    "Villa Giardino",
    "Villa Huidobro",
    "Villa La Bolsa",
    "Villa La Donosa",
    "Villa La Estancuela",
    "Villa La Florida",
    "Villa La Isla",
    "Villa La Torre",
    "Villa La Viña",
    "Villa Las Rosas",
    "Villa Loma Bola",
    "Villa Los Aromos",
    "Villa Los Patrones",
    "Villa María",
    "Villa María del Río Seco",
    "Villa Montesol",
    "Villa Morena",
    "Villa Parque Siquiman",
    "Villa Quillinzo",
    "Villa Rossi",
    "Villa San Esteban",
    "Villa San Isidro",
    "Villa Santa Cruz del Lago",
    "Villa Santa María",
    "Villa Sarmiento",
    "Villa Tulumba",
    "Villa Valeria",
    "Villa de Pocho",
    "Villa de las Rosas",
    "Villa del Prado",
    "Villa del Tala",
    "Villa del Totoral",
    "Villa Yacanto",
    "Wenceslao Escalante",
  ],
  "Corrientes": [
    "Alvear",
    "Bella Vista",
    "Berón de Astrada",
    "Bonpland",
    "Caá Catí",
    "Cazadores Correntinos",
    "Ceibas",
    "Cerrito",
    "Chavarría",
    "Cirro Corrientes",
    "Colonia Carlos Pellegrini",
    "Colonia Cavour",
    "Colonia Libertad",
    "Colonia San Martín",
    "Concepción",
    "Corrientes",
    "Cruz de los Milagros",
    "Curuzú Cuatiá",
    "El Sombrero",
    "Esquina",
    "Estación Torrent",
    "Garruchos",
    "Goya",
    "Herlitzka",
    "Ibahay",
    "Itá Ibaté",
    "Itatí",
    "Ituzaingó",
    "Lavalle",
    "Lomas de Galarza",
    "Loreto",
    "Mariano I. Loza",
    "Mercedes",
    "Mocoretá",
    "Monte Caseros",
    "Muchaskis",
    "Nuestra Señora de Loreto",
    "Ombúes de Lavalle",
    "Palo Seco",
    "Paso de los Libres",
    "Pedro Fernández",
    "Perugorría",
    "Pueblo Libre",
    "Puerto Ayacucho",
    "Puerto Borravieja",
    "Puerto Esperanza",
    "Puerto Júpiter",
    "Puerto Libre",
    "Puerto Mario",
    "Puerto Rico",
    "Puerto San Carlos",
    "Puerto Soley",
    "Punta Porã",
    "Rinconada",
    "Saladas",
    "San Antonio de Itatí",
    "San Carlos",
    "San Cosme",
    "San Luis del Palmar",
    "San Miguel",
    "San Roque",
    "Santa Ana",
    "Santa Lucía",
    "Santo Tomé",
    "Sauce",
    "Tabay",
    "Tapebicuá",
    "Yapeyú",
    "Yatay Tyremo",
  ],
  "Entre Ríos": [
    "Alajero",
    "Alcaraz",
    "Alcaraz Creciente",
    "Alcaraz Norte",
    "Aldea Brasilera",
    "Aldea Eliezer",
    "Aldea Epulef",
    "Aldea Spatzenkutter",
    "Aldea Valle María",
    "Aldea Valiente",
    "Altube",
    "Aranguren",
    "Arroyo Barú",
    "Arroyo Cle",
    "Arroyo Grande",
    "Arroyo Urquiza",
    "Bajada Alegre",
    "Bandingas",
    "Basavilbaso",
    "Bellacourt",
    "Bernardino Rivadavia",
    "Bitácora",
    "Boca de Arroyo",
    "Boca del Río",
    "Bonacco",
    "Bovril",
    "Brazo Largo",
    "Bugres",
    "Calá del Clavo",
    "Calá del Gato",
    "Campedelli",
    "Campichuelo",
    "Cañas",
    "Capilla",
    "Capillitas",
    "Carrizal",
    "Caseros",
    "Cedral",
    "Ceibas",
    "Chajareí",
    "Charigüey",
    "Clodomiro Ledesma",
    "Colon",
    "Colon (Entre Ríos)",
    "Colonia Ayuí",
    "Colonia Ensayo",
    "Colonia Federal",
    "Colonia Hugues",
    "Colonia Las Mercedes",
    "Colonia Mixta",
    "Colonia Raquel",
    "Colonia San Fernando",
    "Colonia San Martín",
    "Colonia San Pedro",
    "Colonia Santa Rosa",
    "Colonia Tunas",
    "Concordia",
    "Conscripto Bernardi",
    "Costa de Nueve",
    "Crespo",
    "Cuchilla Redonda",
    "Curtiembre",
    "Diamante",
    "Don Cristóbal",
    "Don Gonzalo",
    "Dos Arroyos",
    "Durazno",
    "El Brillante",
    "El Congo",
    "El Cruce",
    "El Esquinito",
    "El Gaucho",
    "El Gramillal",
    "El Pingo",
    "El Planchón",
    "El Potrero",
    "El Remate",
    "El Rosario",
    "El Timoteo",
    "El Yasín",
    "Embajador Martínez",
    "Encruzader",
    "Enrique Carbó",
    "Espinillo",
    "Estacas",
    "Estancia Grande",
    "Estación Raíces",
    "Fernández",
    "Federal",
    "Fernando Canal de Bevans",
    "Fray Bentos",
    "Galeras",
    "Garat",
    "Garrido",
    "Gobernador Echagüe",
    "Gobernador Mansilla",
    "Gobernador Sosa",
    "González Calderón",
    "Gualeguay",
    "Gualeguaychú",
    "Gualeguaycito",
    "Guayaquil",
    "Hamberto de Garat",
    "Hasenkamp",
    "Hernandarias",
    "Herrera",
    "Hocker",
    "Huayra Guasú",
    "Ibicuy",
    "Ingeniero Sajaroff",
    "Irazusta",
    "Isla del Cerrito",
    "Jubileo",
    "Kilómetro 10",
    "La Calera",
    "La Chiva",
    "La Esmeralda",
    "La Granja",
    "La Oroya",
    "La Picada",
    "La Providencia",
    "La Serena",
    "La Trinidad",
    "Laguna Benítez",
    "Larroque",
    "Las Garzas",
    "Las Machiras",
    "Las Mercedes",
    "Las Rosas",
    "Lata",
    "Libaros",
    "Libres del Sud",
    "Los Charrúas",
    "Los Conquistadores",
    "Los Indios",
    "Los Laureles",
    "Lucas González",
    "Maciá",
    "María Grande",
    "María Grande (norte)",
    "Medanos",
    "Mendoza",
    "Mercedes",
    "Miguel Torres",
    "Moisés Ville",
    "Montoya",
    "Moreno",
    "Murillo",
    "Nogoyá",
    "Nueva Escocia",
    "Nueva Vizcaya",
    "Óbolo",
    "Ombúes de Lavalle",
    "Open Door",
    "Pagar",
    "Palavecino",
    "Paraná",
    "Paración Grande",
    "Paranacito",
    "Pastor Britos",
    "Pedernal",
    "Pedro Campillo",
    "Pedro Díaz",
    "Piedras Blancas",
    "Piloto",
    "Primera Bajada",
    "Pronunciamiento",
    "Pueblo Brugo",
    "Pueblo General San Martín",
    "Pueblo Liebig",
    "Puerto Alvear",
    "Puerto Bemberg",
    "Puerto Copa",
    "Puerto Curuzú",
    "Puerto Diamante",
    "Puerto Escondido",
    "Puerto Goya",
    "Puerto Las Cuevas",
    "Puerto Libertad",
    "Puerto Oro Verde",
    "Puerto Paraná",
    "Puerto San Julián",
    "Puerto Yacuí",
    "Puiggari",
    "Puisteros",
    "Punta del Tigre",
    "Quebracho",
    "Queen",
    "Quinto Cuartel",
    "Raíces",
    "Racedo",
    "Rincón de Nogoyá",
    "Rincón de Tayata",
    "Rivas",
    "Rocamora",
    "Rodríguez",
    "Roldán",
    "Rosario del Tala",
    "Rumbo",
    "Sáenz Peña",
    "Salto Chico",
    "Salto Grande",
    "San Benito",
    "San Carlos",
    "San Fernando",
    "San Gustavo",
    "San Jaime",
    "San José",
    "San Justo",
    "San Martín",
    "San Salvador",
    "San Víctor",
    "Santa Ana",
    "Santa Elena",
    "Santos Lugares",
    "Sarandi",
    "Sarandi (Entre Ríos)",
    "Sauce de Luna",
    "Seguí",
    "Sir Leonard",
    "Sosa",
    "Strobel",
    "Tabossi",
    "Talita",
    "Tres Bocas",
    "Tres Esquinas",
    "Tres Lagunas",
    "Ubajay",
    "Urdinarrain",
    "Valente",
    "Valentine",
    "Viale",
    "Victoria",
    "Villa Adelina",
    "Villa Allende",
    "Villa Atanasio",
    "Villa Clara",
    "Villa Dominguez",
    "Villa Elisa",
    "Villa Fontana",
    "Villa Gobernador Luis Etchevehere",
    "Villa Hernandarias",
    "Villa Mantero",
    "Villa Paranacito",
    "Villa San Gabriel",
    "Villa San Isidro",
    "Villa Urquiza",
    "Villaguay",
    "Vizcachera",
    "Walter Moss",
    "Xanadú",
    "Yeruá",
    "Yeso",
    "Zárate",
  ],
  "Formosa": [
    "Banco Payaguá",
    "Barranqueras",
    "Berraondo",
    "Blanco Pondal",
    "Buena Vista",
    "Cabulí",
    "Campo del Agua",
    "Campo Grande",
    "Capitán Solá",
    "Clorinda",
    "Colonia Pastoril",
    "Colonia Sanguinetti",
    "Colonia Tirolesa",
    "Comandante Fontana",
    "Coronel Bogado",
    "Corrales",
    "El Acheral",
    "El Espinillo",
    "El Potrillo",
    "El Remate",
    "El Colorado",
    "Espinillo",
    "Formosa",
    "Fortín Sargento Leyes",
    "Guadalcazar",
    "Guaycolec",
    "Herradura",
    "Isla Apando",
    "La Florencia",
    "La Nena",
    "La Planchada",
    "La Rinconada",
    "Laguna Blanca",
    "Laguna Naick-Neck",
    "Lapachito",
    "Las Lomitas",
    "Loma Sánchez",
    "Los Chiriguanes",
    "Mariano Boyle",
    "Misión San Francisco",
    "Misión Tacaaglé",
    "Mojón de Fierro",
    "Moshi",
    "Palma Sola",
    "Palo Santo",
    "Paraje Guayaquil",
    "Paraje San Martín",
    "Piñalito Sur",
    "Posta Camacho",
    "Potrero de los Guascalones",
    "Puerto Misión",
    "Puerto Rico",
    "Puerto Vilelas",
    "Riacho He-He",
    "San Francisco de laishi",
    "San Martín",
    "San Martín 2",
    "Siete Palmas",
    "Subcomisario Elías Yofre",
    "Tatane",
    "Tres Lagunas",
    "Villa Adriana",
    "Villa Delicia",
    "Villa Escolar",
    "Villa General Güemes",
    "Villa Hermosa",
    "Villa Leticia",
    "Villa Maria Bonita",
    "Villa Paraná",
    "Villa Río Bermejito",
    "Villa San Antonio",
    "Villa Trinidad",
  ],
  "Jujuy": [
    "Abra Pampa",
    "Alfarcito",
    "Alto Calixto",
    "Alto de la Frontera",
    "Alto Peñalva",
    "Arroyo Colorado",
    "Atilio V. Imposti",
    "Barcena",
    "Bella Vista",
    "Bermejito",
    "Caimancito",
    "Calilegua",
    "Capitan Catalá",
    "Catua",
    "Cienega",
    "Cobará",
    "Cochinoca",
    "Concepción",
    "Coranzuli",
    "Cusi Cusi",
    "El Aguilar",
    "El Carmelo",
    "El Desmonte",
    "El Piquete",
    "El Talar",
    "Fraile Pintado",
    "Godoy Cruz",
    "Guerrero",
    "Humahuaca",
    "Iconteros",
    "Iscuande",
    "Iturbe",
    "La Armonía",
    "La Ciénaga",
    "La Poma",
    "La Quiaca",
    "La Toma",
    "Las Pampas",
    "Ledesma",
    "Libertador Gral. San Martín",
    "Liliana",
    "Los Alisos",
    "Los Toldos",
    "Maimará",
    "Monte Rico",
    "Moreno",
    "Nazareno",
    "Orán",
    "Oro",
    "Paicone",
    "Palca",
    "Palma Sola",
    "Perico",
    "Piedra del Águila",
    "Pilcomayo",
    "Pozo",
    "Puesto del Marqués",
    "Pumahuasi",
    "Rinconada",
    "Río Blanco",
    "Río Grande",
    "Rodeo",
    "San Antonio",
    "San Francisco",
    "San Francisco de Yacuy",
    "San Jerónimo",
    "San Juan de Oros",
    "San Lucas",
    "San Pedro de Jujuy",
    "Santa Clara",
    "Santa Catalina",
    "Santa Cita",
    "Santuario de Toba",
    "Selva",
    "Sindicato Dodera",
    "Susques",
    "Tafna",
    "Tilcara",
    "Tres Cruces",
    "Tumbaya",
    "Valle Grande",
    "Vinalito",
    "Volcán",
    "Yacoraite",
    "Yavi",
    "Yuto",
  ],
  "La Pampa": [
    "Alpachiri",
    "Alta Italia",
    "Anguil",
    "Arata",
    "Ataliva Roca",
    "Bernardo Larroudé",
    "Bernasconi",
    "Caleufú",
    "Catriló",
    "Chacharramendi",
    "Colonia Barón",
    "Colonia Etcheverry",
    "Colonia La María",
    "Colonia San Miguel",
    "Colonia Santa María",
    "Conhelo",
    "Coronel Hilario Lagos",
    "Cuchillo Co",
    "Doblas",
    "Dorrego",
    "Edugo",
    "Emilio Bunge",
    "Gato Colorado",
    "General Levalle",
    "General Manilio Nicéforo Arias",
    "General Pico",
    "General San Martín",
    "Guatraché",
    "Hucal",
    "Jardín Alanís",
    "Jacinto Arauz",
    "Lamarca",
    "Quemú Quemú",
    "Winifreda",
    "Miguel Riglos",
    "Monte Nievas",
    "Parera",
    "Pichi Howden",
    "Quaraó",
    "Rancul",
    "Realicó",
    "Relmo",
    "Sanguinetti",
    "Santa Isabel",
    "Santa Rosa",
    "Subercaseaux",
    "Telen",
    "Trenel",
    "Uriburu",
    "Veinticinco de Mayo",
    "Victorica",
    "Villa Mirasol",
  ],
  "La Rioja": [
    "Aicuña",
    "Alcazar",
    "Alto Bayo",
    "Alto Feliciano",
    "Aminga",
    "Anillaco",
    "Antinaco",
    "Banda Florida",
    "Bazán",
    "Belen",
    "Bodega Pipiná",
    "Cachí",
    "Campeggi",
    "Chamical",
    "Chilecito",
    "Chuquis",
    "Civital",
    "Comechina",
    "Cuipán",
    "Divisadero",
    "El Abanico",
    "El Barrial",
    "El Capitán",
    "El Chamico",
    "El Peñón",
    "El Puntal",
    "El Retiro",
    "El Sunchal",
    "El Tala",
    "Famatina",
    "General Belgrano",
    "General Godoy",
    "General Ombé",
    "Guandacol",
    "Jagüé",
    "La Cuadra",
    "La Isla",
    "La Merced",
    "La Puerta de San José",
    "La Verde",
    "Las Catitas",
    "Las Padercitas",
    "Los Molinos",
    "Luján",
    "Malligasta",
    "Malcán",
    "Nácori Chico",
    "Nonogasta",
    "Olapa",
    "Punta de los Llanos",
    "Villa Sanagasta",
    "Villa Unión",
    "Vinchina",
  ],
  "Mendoza": [
    "Algarrobo Grande",
    "Altiuy",
    "Arroyo Conlara",
    "Aristides Villanueva",
    "Atuel",
    "Bernasconi",
    "Buenos Aires",
    "Calmú",
    "Camping",
    "Capdevilla",
    "Capiz",
    "Carmenates",
    "Chacras de Coria",
    "Chaparro",
    "Coquimbito",
    "Cruz de Piedra",
    "El Barril",
    "El Carrizal",
    "El Convento",
    "El Plumerillo",
    "El Trapiche",
    "El Vergel",
    "Eugenio Bustos",
    "General Alvear",
    "General Gutiérrez",
    "Godoy Cruz",
    "Gran Mendoza",
    "Guaymallén",
    "Huarpes",
    "Jardín Alto Verde",
    "Jocolí",
    "Junín",
    "La Colonia",
    "La Consulta",
    "La Cuesta",
    "La Flor",
    "La Primavera",
    "Las Cañadas",
    "Las Heras",
    "Las Paredes",
    "Los Compartos",
    "Los Corralitos",
    "Los Indios",
    "Luján de Cuyo",
    "Maipú",
    "Mayor Drummond",
    "Medrano",
    "Monte Comán",
    "Monte Dinero",
    "Ñacuñán",
    "Palmira",
    "Pedro Molina",
    "Pehuenches",
    "Perdriel",
    "Presidente Sarmiento",
    "Puente de Glass",
    "Puente del Inca",
    "Rivadavia",
    "San Carlos",
    "San Martín",
    "San Martín (Mendoza)",
    "Santa Blanca",
    "Santa Rosa",
    "Tupungato",
    "Villa Atuel",
    "Villa Atascosa",
    "Villa Bastias",
    "Villa Cabal",
    "Villa Cañada Seca",
    "Villa El Retiro",
    "Villa El Salvador",
    "Villa General Alvear",
    "Villa La Estancia",
    "Villa La Paz",
    "Villa Moderna",
    "Villa Nueva",
    "Villa Paula",
    "Villa Retiro",
    "Villa San Antonio",
    "Villa San Lorenzo",
    "Villa Teresa",
    "Villa Tulipán",
  ],
  "Misiones": [
    "Alba Posse",
    "Alberdi",
    "Apostoles",
    "Aristóbulo del Valle",
    "Arroyo del Medio",
    "Azara",
    "Barra Concepción",
    "Bernardo de Irigoyen",
    "Bonpland",
    "Caá Yari",
    "Cambyretá",
    "Capioví",
    "Caraguatay",
    "Cerro Azul",
    "Cerro Corá",
    "Colonia Alvear",
    "Colonia Aurora",
    "Colonia Belgrano",
    "Colonia Carlos Pellegrini",
    "Colonia San Alberto",
    "Concepción de la Sierra",
    "Concordia",
    "Cruce Caballero",
    "El Alcázar",
    "El Dorado",
    "El Soberbio",
    "Eldorado",
    "Fachinal",
    "Fernández",
    "Garuhapé",
    "Garupá",
    "General Alvear",
    "General Belgrano",
    "General Juan José Viamonte",
    "General San Martín",
    "Gobernador Roca",
    "Guaraní",
    "Helvecia",
    "Hipolito Yrigoyen",
    "Itacaruaré",
    "Jardín América",
    "Lavalle",
    "Leandro N. Alem",
    "Loreto",
    "Los Helechos",
    "Montecarlo",
    "Oberá",
    "Ombúes de Lavalle",
    "Panambí",
    "Picada Bonita",
    "Posadas",
    "Puerto Esperanza",
    "Puerto Federación",
    "Puerto Iguazú",
    "Puerto Mado",
    "Puerto Rico",
    "Puerto Victoria",
    "Roosevelt",
    "San Antonio",
    "San Francisco",
    "San Javier",
    "San Martín",
    "San Pedro",
    "Santa Ana",
    "Santa María",
    "Santo Pipó",
    "Tres Cruces",
    "Villa Argañaraz",
    "Villa Bonita",
    "Villa del Lago",
    "Villa Francia",
    "Villa Lanús",
    "Villa Manguera",
    "Villa Paraná",
    "Villa Yacuy",
  ],
  "Neuquén": [
    "Aldea Beleiro",
    "Aldea Epulef",
    "Añelo",
    "Bajada del Agrio",
    "Barrancas",
    "Bavio Grande",
    "Caello",
    "Caviahue",
    "Centenario",
    "Chichinales",
    "Chos Malal",
    "Cipolletti",
    "Covunco",
    "Cutral Có",
    "El Cholar",
    "El Huecú",
    "El Sauce",
    "Fortín Mostyn",
    "Huampum",
    "Huinganco",
    "Junín de los Andes",
    "Las Lajas",
    "Las Ovejas",
    "Loncopué",
    "Los Catalogos",
    "Los Chihuidos",
    "Mancha Popular",
    "Mariano Moreno",
    "Maquinchao",
    "Martínez de Rozas",
    "Neuquén",
    "Oñanko",
    "Paso Aguerre",
    "Pichi Neuquén",
    "Picún Leufú",
    "Piedra del Águila",
    "Plaza Huincul",
    "Plottier",
    "Portezuelo",
    "Rincón de Los Sauces",
    "San Martín de los Andes",
    "San Patricio del Chañar",
    "Sandra",
    "Sauzal Bonito",
    "Senillosa",
    "Taquimilán",
    "Tricao Malal",
    "Varvarco",
    "Villa Curruhuinca",
    "Villa El Cholar",
    "Villa La Angostura",
    "Villa Manzano",
    "Villa Pehuenia",
    "Villa Regina",
    "Vista Alegre",
  ],
  "Río Negro": [
    "Aguada Cecilio",
    "Aguada de Guerra",
    "Aguada Guanaco",
    "Allen",
    "Angostura",
    "Arroyo los Berros",
    "Barrio de los Pinos",
    "Barrio Militar",
    "Cervantes",
    "Chichinales",
    "Chimpay",
    "Choele Choel",
    "Cipolletti",
    "Colonia Colorado Grande",
    "Colonia Juliá y Echarren",
    "Coronel Belisle",
    "Cuartel V",
    "Darwin",
    "General Conesa",
    "General Enrique Godoy",
    "General Roca",
    "Huanguelén",
    "Ingeniero Luis A. Huergo",
    "Lamarque",
    "Los Menucos",
    "Mainqué",
    "María Blanco Suárez",
    "Maquinchao",
    "Negrete",
    "Palmira",
    "Pilar",
    "Presidente Roca",
    "Río Colorado",
    "Río Negro",
    "Sauce Blanco",
    "Sierra Colorada",
    "Treneta",
    "Valcheta",
    "Viedma",
    "Villa Alberdi",
    "Villa Amalia",
    "Villa El Chocon",
    "Villa General Roca",
    "Villa Lelques",
    "Villa Mascardi",
    "Villa Regina",
    "Villa San Isidro",
    "Villa San José",
    "Villa Unión",
  ],
  "Salta": [
    "Aguaray",
    "Angastaco",
    "Animana",
    "Cachi",
    "Cafayate",
    "Campo Quijano",
    "Cerrillos",
    "Chicoana",
    "Cobra",
    "Colonia Santa Rosa",
    "El Carril",
    "El Galpón",
    "El Potrero",
    "El Tunal",
    "General Güemes",
    "General Mosconi",
    "Guachipas",
    "Hipólito Yrigoyen",
    "Iruya",
    "Joaquín V. González",
    "La Caldera",
    "La Candelaria",
    "La Estación",
    "La Merced",
    "La Puerta",
    "La Viña",
    "Las Lajitas",
    "Los Toldos",
    "Métán",
    "Molinos",
    "Orán",
    "Pacachi",
    "Pichanal",
    "Rivadavia",
    "Rosario de Lerma",
    "Salta",
    "San Antonio de los Cobres",
    "San Carlos",
    "San José de Metán",
    "San Lorenzo",
    "Santa Victoria",
    "Seclantás",
    "Tartagal",
    "Tolar Grande",
    "Urundel",
    "Vaqueros",
    "Villa San Lorenzo",
  ],
  "San Juan": [
    "Albardón",
    "Angaco",
    "Calingasta",
    "Caucete",
    "Chimbas",
    "Granja de Poanzón",
    "Iglesia",
    "Jáchal",
    "Pocito",
    "Rawson",
    "Rivadavia",
    "San Martín",
    "Santa Lucía",
    "Sarmiento",
    "Ullum",
    "Valle Fértil",
    "Veinticinco de Mayo",
    "Villa Basilio Nievas",
    "Villa de la Quebrada",
    "Villa del Carmen",
    "Villa General Belgrano",
    "Villa Gral. Alvear",
    "Villa Ibáñez",
    "Villa Malvinas Argentinas",
    "Villa Media Agua",
    "Villa Paula Sarmiento",
    "Villa San Agustín",
    "Villa San José de Vinchina",
    "Villa Santa Rosa",
    "Villa Turismo",
    "Zonda",
  ],
  "San Luis": [
    "Alto Pencoso",
    "Anchorena",
    "Arizona",
    "Batavia",
    "Beazley",
    "Buena Esperanza",
    "Caldenadas",
    "Candelaria",
    "Carolina",
    "Chancar",
    "Chimbas",
    "Clementón",
    "Colonia Barraquero",
    "Colonia Rodolfo Martínez",
    "Concarán",
    "Cortaderas",
    "El Morro",
    "El Volcán",
    "Fortín El Patria",
    "Fraga",
    "Furnias",
    "Granel",
    "Juana Koslay",
    "La Carolina",
    "La Majada",
    "La Punta",
    "La Toma",
    "Las Aguadas",
    "Las Lagunas",
    "Las Vertientes",
    "Lavaisse",
    "Leandro N. Alem",
    "Los Molles",
    "Luján",
    "Maquinista Savio",
    "Naschel",
    "Nava",
    "Paisano",
    "Palmira",
    "Papagayos",
    "Paso Grande",
    "Potrerillo",
    "Quines",
    "Renca",
    "Río Grande",
    "Saladillo",
    "San Francisco del Monte de Oro",
    "San Gerónimo",
    "San Luis",
    "San Martín",
    "San Pablo",
    "Santa Rosa",
    "Suyuque",
    "Talita",
    "Tobares",
    "Travesía",
    "Tucunaco",
    "Unión",
    "Villa de la Quebrada",
    "Villa de la Punta",
    "Villa del Carmen",
    "Villa General Roca",
    "Villa Larca",
    "Villa Mercedes",
    "Villa de San Isidro",
  ],
  "Santa Cruz": [
    "28 de Noviembre",
    "Bajo Caracoles",
    "Caleta Olivia",
    "Cañadón Seco",
    "Comandante Piedra Buena",
    "El Calafate",
    "El Chaltén",
    "El Pluma",
    "Gobernador Gregores",
    "Hipólito Yrigoyen",
    "Jaramillo",
    "Koluel Kaike",
    "Las Heras",
    "Los Antiguos",
    "Perito Moreno",
    "Pico Truncado",
    "Puerto Deseado",
    "Puerto San Julián",
    "Puerto Santa Cruz",
    "Río Cuarto",
    "Río Gallegos",
    "Río Turbio",
    "Tres Lagos",
    "Veintiocho de Noviembre",
    "Yacimientos Río Turbio",
  ],
  "Santa Fe": [
    "Aldao",
    "Alcorta",
    "Alvear",
    "Arequito",
    "Arminda",
    "Arroyo Seco",
    "Avellaneda",
    "Barrancas",
    "Barrio Barranca Yaco",
    "Barrio Cerveza Helada",
    "Bigand",
    "Bouquet",
    "Bustinza",
    "Capitán Bermúdez",
    "Carmen",
    "Carreras",
    "Cayastá",
    "Cayastacito",
    "Centeno",
    "Ceres",
    "Chabás",
    "Chañar Ladeado",
    "Christophersen",
    "Clark",
    "Colonia Anaheim",
    "Colonia Bossi",
    "Colonia Cavour",
    "Colonia Celina",
    "Colonia Durán",
    "Colonia Margarita",
    "Colonia Raquel",
    "Colonia San José",
    "Colonia Tacurú Pucú",
    "Constanza",
    "Coronda",
    "Coronel Arnold",
    "Coronel Bogado",
    "Coronel Fraga",
    "Coronda",
    "Cuatro Esquinas",
    "Desmochades",
    "Díaz",
    "Egusquiza",
    "El Rabón",
    "El Trébol",
    "Esperanza",
    "Estación Clucellas",
    "Estación Saguier",
    "Eusebia y Carolina",
    "Felicia",
    "Firmat",
    "Fray Luis Beltrán",
    "Fuentes",
    "Garibaldi",
    "Gato Colorado",
    "General Lagos",
    "Gessler",
    "Gödeken",
    "Gálvez",
    "Helvecia",
    "Hersilia",
    "Hipólito Bouchard",
    "Hugentobler",
    "Humboldt",
    "Ibarlucea",
    "Ingeniero Chanourdie",
    "Iriondo",
    "Juan de Garay",
    "La Brava",
    "La Cabral",
    "La Lucila",
    "Labordeboy",
    "Laguna Paiva",
    "Landeta",
    "Larrechea",
    "Las Arpas",
    "Las Bandurrias",
    "Las Garzas",
    "Las Rosas",
    "Lazzarino",
    "Lehmann",
    "Libertad",
    "Llambi Campbell",
    "Lobón",
    "Loma Alta",
    "López",
    "Maciel",
    "Manucho",
    "María Eugenia",
    "María Teresa",
    "Maxi Norte",
    "Melincué",
    "Miguel Torres",
    "Monte Vera",
    "Monje",
    "Nelson",
    "Niqueto",
    "Noelia",
    "Nueva Italia",
    "Nueva Palmira",
    "Nuevo Torino",
    "Ombúes de Lavalle",
    "Paraje La Virginia",
    "Pedro Gómez Cello",
    "Pérez",
    "Peyrano",
    "Piamonte",
    "Pilar",
    "Piñeyro",
    "Plaza Clucellas",
    "Portugués",
    "Pozo Borrado",
    "Presidente Roca",
    "Pujato",
    "Punta Porã",
    "Rivadavia",
    "Roldán",
    "Romang",
    "Rosario",
    "Rufino",
    "Saguier",
    "Saladero Mariano Cabal",
    "San Antonio de Arredondo",
    "San Carlos Centro",
    "San Carlos del Norte",
    "San Cristóbal",
    "San Eugenio",
    "San Fabián",
    "San Genaro",
    "San Genaro Norte",
    "San Jerónimo del Sauce",
    "San Jerónimo Norte",
    "San Jorge",
    "San Justo",
    "San Lorenzo",
    "San Mariano",
    "San Martín de las Escobas",
    "San Martín Norte",
    "San Vicente",
    "Sancti Spiritu",
    "Santa Fe",
    "Santaeufemia",
    "Santo Domingo",
    "Santo Tomé",
    "Sargento Cabral",
    "Sarmiento",
    "Sastre",
    "Sauce Viejo",
    "Serodino",
    "Silva",
    "Soldini",
    "Soledad",
    "Susana",
    "Tacuarendi",
    "Tacural",
    "Tartagal",
    "Teodelina",
    "Tostado",
    "Totoras",
    "Toyos",
    "Tres Arroyos",
    "Tres Esquinas",
    "Vila",
    "Villa Aldama",
    "Villa Atamisqui",
    "Villa Cañás",
    "Villa del Carmen",
    "Villa Elvira",
    "Villa Gobernador Gálvez",
    "Villa Goberdosa",
    "Villa Guillermina",
    "Villa Minetti",
    "Villa Mugueta",
    "Villa Ojo de Agua",
    "Villa Regules",
    "Villa San José",
    "Villa Sara",
    "Villa Trinidad",
    "Villa Urquiza",
    "Wheelwright",
    "Zavalla",
  ],
  "Santiago del Estero": [
    "Abra Grande",
    "Ahi Veremos",
    "Alpampas",
    "Ancajá",
    "Angelina",
    "Antajé",
    "Ardiles",
    "Beltrán",
    "Brea Pozo",
    "Cachi Huasi",
    "Cachicora",
    "Campo de Cejas",
    "Castellanos",
    "Cejas",
    "Chañar Pozo",
    "Chuique",
    "Clojatas",
    "Colonia Dora",
    "Colonia El Simbolar",
    "Colonia San Pedro",
    "Córdoba",
    "El Añil",
    "El Bobadal",
    "El Cejote",
    "El Colorado",
    "El Impenetrable",
    "El Mollár",
    "El Moño",
    "El Nazareno",
    "El Roble",
    "El Talar",
    "Fernández",
    "Fortín Inca",
    "Frías",
    "Garza",
    "Gramilla",
    "Guampata",
    "Guasayán",
    "Herrera",
    "Huyamampa",
    "Icaño",
    "Ingeniero Matías Sánchez",
    "Inti Huasi",
    "Ivarez",
    "Jesús María",
    "La Banda",
    "La Cañada",
    "La Dársena",
    "La Nena",
    "La Nueva Costa",
    "La Punta",
    "La Regional",
    "La Simoca",
    "Laprida",
    "Las Cejas",
    "Las Delicias",
    "Las Lajitas",
    "Las Palmitas",
    "Lavalle",
    "Legaspe",
    "Lomitas",
    "Los Jiménez",
    "Los Nuñez",
    "Loreto",
    "Maco",
    "Mailín",
    "Manogasta",
    "Maquito",
    "Maravilla",
    "Media Agua",
    "Monte Quemado",
    "Morales",
    "Nueva Esperanza",
    "Nueva Francia",
    "Nueva España",
    "Obispo Aneyral",
    "Ojo de Agua",
    "Pampa de Los Guanacos",
    "Palo Negro",
    "Pampa Atún",
    "Paso Grande",
    "Pinto",
    "Pozo Hondo",
    "Puente Nacional",
    "Pueblos",
    "Punta de Agua",
    "Quimili",
    "Real Sayana",
    "Río Hondo",
    "Robles",
    "Salavina",
    "San Andrés",
    "San Francisco de los Quiroga",
    "San José del Boquerón",
    "San Pedro",
    "San Pedro de Guasayán",
    "San Ramón",
    "San Roque",
    "Santiago del Estero",
    "Santos Lugares",
    "Simsan",
    "Smata",
    "Sumampa",
    "Suncho Corral",
    "Taboada",
    "Tapso",
    "Termas de Río Hondo",
    "Tintina",
    "Tiraxi",
    "Tramontana",
    "Tres Bocas",
    "Tusca Bajada",
    "Urutau",
    "Vaca Huancu",
    "Villa Atamisqui",
    "Villa Eloísa",
    "Villa Figueroa",
    "Villa Guasayán",
    "Villa Jiménez",
    "Villa La Punta",
    "Villa Mitre",
    "Villa Ojo de Agua",
    "Villa Quinteros",
    "Villa San Martín",
    "Villa Sara",
    "Villa Unión",
    "Vinalito",
    "Vinara",
    "Víctor Junco",
    "Villa Salavina",
    "Yuchan",
  ],
  "Tierra del Fuego": [
    "Cerro Sombrero",
    "Los Eclaireurs",
    "Luego Río Grande",
    "Paraíso",
    "Puerto Harberton",
    "Puerto Navarro",
    "Río Grande",
    "San Sebastián",
    "Santa Cruz",
    "Tolhuin",
    "Ushuaia",
  ],
  "Tucumán": [
    "Aguilares",
    "Alpachiri",
    "Alto de Medina",
    "Alto Verde",
    "Arcadia",
    "Atahona",
    "Banda del Río Salí",
    "Barrio San José",
    "Belen",
    "Buena Vista",
    "Capitán Cáceres",
    "Cevil Redondo",
    "Chicligasta",
    "Concepción",
    "Del Fresco",
    "El Bracho",
    "El Cadillal",
    "El Chañar",
    "El Manantial",
    "El Méndez",
    "El Mojón",
    "El Naranjal",
    "El Puestito",
    "El Sacrificio",
    "El Sunchal",
    "El Tostado",
    "El Zárate",
    "Garmendia",
    "Graneros",
    "Icaño",
    "Juan B. Alberdi",
    "La Cocha",
    "La Estancia",
    "La Florida",
    "La Matanza",
    "La Ramada",
    "La Ramada Norte",
    "Las Talitas",
    "Leocadio Paz",
    "Los Aguirre",
    "Los Nogales",
    "Los Ralos",
    "Lules",
    "María Elena",
    "Medina",
    "Monteagudo",
    "Monteros",
    "Palo Marcado",
    "Pampa del Indio",
    "Piedrabuena",
    "Raco",
    "Ranchillos",
    "Rio Colorado",
    "Rio Seco",
    "Rumi Punco",
    "San Andrés",
    "San Felipe",
    "San Gerónimo",
    "San Ignacio",
    "San Javier",
    "San José de la Dormida",
    "San Miguel de Tucumán",
    "San Pablo",
    "San Pedro de Guasayán",
    "Santa Ana",
    "Santa Lucía",
    "Santa María de Pisimí",
    "Santiago del Estero",
    "Sargentillo",
    "Simoca",
    "Taco Ralos",
    "Tafí del Valle",
    "Tafí Viejo",
    "Tapia",
    "Tartagal",
    "Tinco",
    "Trancas",
    "Urundel",
    "Villa Carmela",
    "Villa Quinteros",
    "Yerba Buena",
    "Yucumanita",
  ],
};

export const getLocalitiesByProvince = (province: string): string[] => {
  return localities[province] || [];
};
